module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "ExplosionGround_00010.png",
				spriteColorRect = { x = 0, y = 0, width = 125, height = 160 }, 
				textureRect = { x = 0, y = 0, width = 125, height = 160 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00012.png",
				spriteColorRect = { x = 46, y = 122, width = 31, height = 38 }, 
				textureRect = { x = 403, y = 98, width = 31, height = 38 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00014.png",
				spriteColorRect = { x = 30, y = 80, width = 65, height = 80 }, 
				textureRect = { x = 811, y = 76, width = 65, height = 80 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00016.png",
				spriteColorRect = { x = 22, y = 70, width = 79, height = 90 }, 
				textureRect = { x = 667, y = 378, width = 79, height = 90 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00018.png",
				spriteColorRect = { x = 17, y = 64, width = 89, height = 96 }, 
				textureRect = { x = 391, y = 0, width = 89, height = 96 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00020.png",
				spriteColorRect = { x = 16, y = 58, width = 89, height = 102 }, 
				textureRect = { x = 636, y = 182, width = 89, height = 102 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00022.png",
				spriteColorRect = { x = 16, y = 54, width = 89, height = 106 }, 
				textureRect = { x = 636, y = 74, width = 89, height = 106 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00024.png",
				spriteColorRect = { x = 17, y = 50, width = 91, height = 110 }, 
				textureRect = { x = 557, y = 338, width = 91, height = 110 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00026.png",
				spriteColorRect = { x = 21, y = 46, width = 89, height = 114 }, 
				textureRect = { x = 545, y = 80, width = 89, height = 114 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00028.png",
				spriteColorRect = { x = 18, y = 44, width = 93, height = 116 }, 
				textureRect = { x = 541, y = 220, width = 93, height = 116 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00030.png",
				spriteColorRect = { x = 17, y = 40, width = 93, height = 120 }, 
				textureRect = { x = 450, y = 98, width = 93, height = 120 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00032.png",
				spriteColorRect = { x = 14, y = 38, width = 97, height = 122 }, 
				textureRect = { x = 442, y = 262, width = 97, height = 122 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00034.png",
				spriteColorRect = { x = 11, y = 36, width = 101, height = 124 }, 
				textureRect = { x = 339, y = 262, width = 101, height = 124 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00036.png",
				spriteColorRect = { x = 7, y = 34, width = 105, height = 126 }, 
				textureRect = { x = 230, y = 152, width = 105, height = 126 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00038.png",
				spriteColorRect = { x = 5, y = 34, width = 109, height = 126 }, 
				textureRect = { x = 115, y = 290, width = 109, height = 126 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00040.png",
				spriteColorRect = { x = 3, y = 34, width = 113, height = 126 }, 
				textureRect = { x = 0, y = 162, width = 113, height = 126 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00042.png",
				spriteColorRect = { x = 2, y = 34, width = 113, height = 126 }, 
				textureRect = { x = 0, y = 290, width = 113, height = 126 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00044.png",
				spriteColorRect = { x = 3, y = 34, width = 113, height = 126 }, 
				textureRect = { x = 115, y = 162, width = 113, height = 126 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00046.png",
				spriteColorRect = { x = 4, y = 35, width = 111, height = 122 }, 
				textureRect = { x = 226, y = 290, width = 111, height = 122 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00048.png",
				spriteColorRect = { x = 6, y = 35, width = 111, height = 118 }, 
				textureRect = { x = 337, y = 142, width = 111, height = 118 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00050.png",
				spriteColorRect = { x = 7, y = 35, width = 111, height = 102 }, 
				textureRect = { x = 444, y = 386, width = 111, height = 102 }, 
				spriteSourceSize = { width = 125, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00000.png",
				spriteColorRect = { x = 68, y = 38, width = 36, height = 12 }, 
				textureRect = { x = 325, y = 128, width = 36, height = 12 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00002.png",
				spriteColorRect = { x = 56, y = 31, width = 76, height = 24 }, 
				textureRect = { x = 325, y = 102, width = 76, height = 24 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00004.png",
				spriteColorRect = { x = 46, y = 24, width = 92, height = 38 }, 
				textureRect = { x = 231, y = 102, width = 92, height = 38 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00006.png",
				spriteColorRect = { x = 40, y = 16, width = 102, height = 48 }, 
				textureRect = { x = 127, y = 102, width = 102, height = 48 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00008.png",
				spriteColorRect = { x = 36, y = 10, width = 108, height = 60 }, 
				textureRect = { x = 557, y = 450, width = 108, height = 60 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00010.png",
				spriteColorRect = { x = 35, y = 6, width = 108, height = 72 }, 
				textureRect = { x = 584, y = 0, width = 108, height = 72 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00012.png",
				spriteColorRect = { x = 36, y = 0, width = 108, height = 88 }, 
				textureRect = { x = 104, y = 418, width = 108, height = 88 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00014.png",
				spriteColorRect = { x = 20, y = 0, width = 126, height = 100 }, 
				textureRect = { x = 263, y = 0, width = 126, height = 100 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00016.png",
				spriteColorRect = { x = 9, y = 0, width = 134, height = 100 }, 
				textureRect = { x = 127, y = 0, width = 134, height = 100 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00018.png",
				spriteColorRect = { x = 15, y = 1, width = 126, height = 98 }, 
				textureRect = { x = 316, y = 414, width = 126, height = 98 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00020.png",
				spriteColorRect = { x = 31, y = 7, width = 82, height = 90 }, 
				textureRect = { x = 650, y = 286, width = 82, height = 90 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00022.png",
				spriteColorRect = { x = 14, y = 5, width = 100, height = 92 }, 
				textureRect = { x = 214, y = 418, width = 100, height = 92 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00024.png",
				spriteColorRect = { x = 11, y = 3, width = 102, height = 94 }, 
				textureRect = { x = 0, y = 418, width = 102, height = 94 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00026.png",
				spriteColorRect = { x = 12, y = 2, width = 100, height = 78 }, 
				textureRect = { x = 482, y = 0, width = 100, height = 78 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00028.png",
				spriteColorRect = { x = 33, y = 5, width = 80, height = 76 }, 
				textureRect = { x = 734, y = 234, width = 80, height = 76 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00030.png",
				spriteColorRect = { x = 33, y = 5, width = 82, height = 78 }, 
				textureRect = { x = 727, y = 154, width = 82, height = 78 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00032.png",
				spriteColorRect = { x = 33, y = 9, width = 82, height = 78 }, 
				textureRect = { x = 727, y = 74, width = 82, height = 78 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00034.png",
				spriteColorRect = { x = 34, y = 15, width = 80, height = 74 }, 
				textureRect = { x = 811, y = 0, width = 80, height = 74 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00036.png",
				spriteColorRect = { x = 43, y = 12, width = 68, height = 72 }, 
				textureRect = { x = 694, y = 0, width = 68, height = 72 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00038.png",
				spriteColorRect = { x = 44, y = 8, width = 64, height = 78 }, 
				textureRect = { x = 748, y = 312, width = 64, height = 78 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00040.png",
				spriteColorRect = { x = 46, y = 5, width = 62, height = 80 }, 
				textureRect = { x = 748, y = 392, width = 62, height = 80 }, 
				spriteSourceSize = { width = 150, height = 100 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end