module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "ExplosionGround_00010.png",
				spriteColorRect = { x = 0, y = 0, width = 63, height = 80 }, 
				textureRect = { x = 0, y = 0, width = 63, height = 80 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00012.png",
				spriteColorRect = { x = 24, y = 62, width = 15, height = 18 }, 
				textureRect = { x = 106, y = 62, width = 15, height = 18 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00014.png",
				spriteColorRect = { x = 15, y = 40, width = 33, height = 40 }, 
				textureRect = { x = 408, y = 214, width = 33, height = 40 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00016.png",
				spriteColorRect = { x = 11, y = 34, width = 41, height = 46 }, 
				textureRect = { x = 377, y = 42, width = 41, height = 46 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00018.png",
				spriteColorRect = { x = 8, y = 32, width = 45, height = 48 }, 
				textureRect = { x = 285, y = 54, width = 45, height = 48 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00020.png",
				spriteColorRect = { x = 9, y = 30, width = 45, height = 50 }, 
				textureRect = { x = 187, y = 0, width = 45, height = 50 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00022.png",
				spriteColorRect = { x = 9, y = 28, width = 43, height = 52 }, 
				textureRect = { x = 285, y = 0, width = 43, height = 52 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00024.png",
				spriteColorRect = { x = 8, y = 26, width = 47, height = 54 }, 
				textureRect = { x = 187, y = 74, width = 47, height = 54 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00026.png",
				spriteColorRect = { x = 10, y = 24, width = 45, height = 56 }, 
				textureRect = { x = 283, y = 184, width = 45, height = 56 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00028.png",
				spriteColorRect = { x = 10, y = 22, width = 45, height = 58 }, 
				textureRect = { x = 281, y = 124, width = 45, height = 58 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00030.png",
				spriteColorRect = { x = 8, y = 20, width = 47, height = 60 }, 
				textureRect = { x = 236, y = 62, width = 47, height = 60 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00032.png",
				spriteColorRect = { x = 7, y = 20, width = 49, height = 60 }, 
				textureRect = { x = 234, y = 0, width = 49, height = 60 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00034.png",
				spriteColorRect = { x = 6, y = 18, width = 51, height = 62 }, 
				textureRect = { x = 230, y = 194, width = 51, height = 62 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00036.png",
				spriteColorRect = { x = 4, y = 18, width = 53, height = 62 }, 
				textureRect = { x = 171, y = 130, width = 53, height = 62 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00038.png",
				spriteColorRect = { x = 3, y = 18, width = 53, height = 62 }, 
				textureRect = { x = 226, y = 130, width = 53, height = 62 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00040.png",
				spriteColorRect = { x = 2, y = 18, width = 55, height = 62 }, 
				textureRect = { x = 57, y = 144, width = 55, height = 62 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00042.png",
				spriteColorRect = { x = 2, y = 18, width = 55, height = 62 }, 
				textureRect = { x = 114, y = 134, width = 55, height = 62 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00044.png",
				spriteColorRect = { x = 2, y = 18, width = 55, height = 62 }, 
				textureRect = { x = 0, y = 144, width = 55, height = 62 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00046.png",
				spriteColorRect = { x = 3, y = 18, width = 55, height = 60 }, 
				textureRect = { x = 65, y = 0, width = 55, height = 60 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00048.png",
				spriteColorRect = { x = 3, y = 18, width = 57, height = 60 }, 
				textureRect = { x = 0, y = 82, width = 57, height = 60 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionGround_00050.png",
				spriteColorRect = { x = 3, y = 18, width = 57, height = 50 }, 
				textureRect = { x = 128, y = 78, width = 57, height = 50 }, 
				spriteSourceSize = { width = 63, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00000.png",
				spriteColorRect = { x = 34, y = 19, width = 19, height = 6 }, 
				textureRect = { x = 59, y = 134, width = 19, height = 6 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00002.png",
				spriteColorRect = { x = 28, y = 15, width = 39, height = 14 }, 
				textureRect = { x = 65, y = 62, width = 39, height = 14 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00004.png",
				spriteColorRect = { x = 23, y = 12, width = 47, height = 20 }, 
				textureRect = { x = 176, y = 52, width = 47, height = 20 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00006.png",
				spriteColorRect = { x = 20, y = 8, width = 51, height = 24 }, 
				textureRect = { x = 123, y = 52, width = 51, height = 24 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00008.png",
				spriteColorRect = { x = 18, y = 5, width = 55, height = 30 }, 
				textureRect = { x = 328, y = 142, width = 55, height = 30 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00010.png",
				spriteColorRect = { x = 17, y = 3, width = 55, height = 36 }, 
				textureRect = { x = 328, y = 104, width = 55, height = 36 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00012.png",
				spriteColorRect = { x = 18, y = 0, width = 55, height = 44 }, 
				textureRect = { x = 108, y = 208, width = 55, height = 44 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00014.png",
				spriteColorRect = { x = 10, y = 0, width = 63, height = 50 }, 
				textureRect = { x = 165, y = 198, width = 63, height = 50 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00016.png",
				spriteColorRect = { x = 4, y = 0, width = 67, height = 50 }, 
				textureRect = { x = 59, y = 82, width = 67, height = 50 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00018.png",
				spriteColorRect = { x = 7, y = 0, width = 63, height = 50 }, 
				textureRect = { x = 122, y = 0, width = 63, height = 50 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00020.png",
				spriteColorRect = { x = 15, y = 3, width = 43, height = 46 }, 
				textureRect = { x = 332, y = 42, width = 43, height = 46 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00022.png",
				spriteColorRect = { x = 7, y = 2, width = 51, height = 48 }, 
				textureRect = { x = 55, y = 208, width = 51, height = 48 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00024.png",
				spriteColorRect = { x = 5, y = 1, width = 53, height = 48 }, 
				textureRect = { x = 0, y = 208, width = 53, height = 48 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00026.png",
				spriteColorRect = { x = 6, y = 1, width = 51, height = 40 }, 
				textureRect = { x = 330, y = 0, width = 51, height = 40 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00028.png",
				spriteColorRect = { x = 17, y = 2, width = 41, height = 40 }, 
				textureRect = { x = 330, y = 216, width = 41, height = 40 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00030.png",
				spriteColorRect = { x = 16, y = 2, width = 41, height = 40 }, 
				textureRect = { x = 330, y = 174, width = 41, height = 40 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00032.png",
				spriteColorRect = { x = 16, y = 4, width = 41, height = 40 }, 
				textureRect = { x = 383, y = 0, width = 41, height = 40 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00034.png",
				spriteColorRect = { x = 17, y = 7, width = 41, height = 38 }, 
				textureRect = { x = 373, y = 174, width = 41, height = 38 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00036.png",
				spriteColorRect = { x = 21, y = 6, width = 35, height = 36 }, 
				textureRect = { x = 385, y = 134, width = 35, height = 36 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00038.png",
				spriteColorRect = { x = 22, y = 4, width = 33, height = 40 }, 
				textureRect = { x = 373, y = 214, width = 33, height = 40 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "ExplosionMissile_00040.png",
				spriteColorRect = { x = 23, y = 2, width = 31, height = 42 }, 
				textureRect = { x = 385, y = 90, width = 31, height = 42 }, 
				spriteSourceSize = { width = 75, height = 50 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end